# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_client.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(300, 300))
        MainWindow.setMaximumSize(QtCore.QSize(400, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_sendPing = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sendPing.setObjectName("pushButton_sendPing")
        self.gridLayout.addWidget(self.pushButton_sendPing, 0, 0, 1, 1)
        self.label_response = QtWidgets.QLabel(self.centralwidget)
        self.label_response.setAlignment(QtCore.Qt.AlignCenter)
        self.label_response.setObjectName("label_response")
        self.gridLayout.addWidget(self.label_response, 1, 0, 1, 1)
        self.pushButton_am_mod = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_am_mod.setObjectName("pushButton_am_mod")
        self.gridLayout.addWidget(self.pushButton_am_mod, 2, 0, 1, 1)
        self.label_am_mod_length = QtWidgets.QLabel(self.centralwidget)
        self.label_am_mod_length.setAlignment(QtCore.Qt.AlignCenter)
        self.label_am_mod_length.setObjectName("label_am_mod_length")
        self.gridLayout.addWidget(self.label_am_mod_length, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 30))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_quit = QtWidgets.QAction(MainWindow)
        self.action_quit.setObjectName("action_quit")
        self.action_aboutApp = QtWidgets.QAction(MainWindow)
        self.action_aboutApp.setObjectName("action_aboutApp")
        self.action_aboutQt = QtWidgets.QAction(MainWindow)
        self.action_aboutQt.setObjectName("action_aboutQt")
        self.menu_File.addAction(self.action_quit)
        self.menu_Help.addAction(self.action_aboutApp)
        self.menu_Help.addAction(self.action_aboutQt)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VERY Simple JSON-RPC Client"))
        self.pushButton_sendPing.setText(_translate("MainWindow", "Send PING"))
        self.label_response.setText(_translate("MainWindow", "Waiting for response..."))
        self.pushButton_am_mod.setText(_translate("MainWindow", "AM Modulation"))
        self.label_am_mod_length.setText(_translate("MainWindow", "Length = 0"))
        self.menu_File.setTitle(_translate("MainWindow", "File"))
        self.menu_Help.setTitle(_translate("MainWindow", "Help"))
        self.action_quit.setText(_translate("MainWindow", "Quit"))
        self.action_quit.setToolTip(_translate("MainWindow", "&Quit"))
        self.action_quit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_aboutApp.setText(_translate("MainWindow", "About..."))
        self.action_aboutApp.setToolTip(_translate("MainWindow", "About"))
        self.action_aboutQt.setText(_translate("MainWindow", "About Qt..."))
        self.action_aboutQt.setToolTip(_translate("MainWindow", "About Qt..."))
